### ISSUE TITLE
[Suggestion] Downloading and installing old UI in linux

### ISSUE THREAD

**Issue by whyimlonely** [SpotX-Official/SpotX-Bash#19]
Like in spotx for windows, which downloads older version of Spoitfy from uptodown and patches it, can the same be applied with this.

Source for older version:
http://repository.spotify.com/pool/non-free/s/spotify-client/spotify-client_1.2.13.661.ga588f749_amd64.deb
(although 404)

But there archive of it 
https://web.archive.org/web/20230629002409if_/http://repository.spotify.com/pool/non-free/s/spotify-client/spotify-client_1.2.13.661.ga588f749_amd64.deb
And the link works, maybe this deb can be archived in this repository and downloaded/installed supporting the old version like the ones for macos and windows.

**Comment by jetfir3** [comment]
SpotX for Windows does not download old versions from 3rd party file hosts, all Windows installations are still hosted directly on the Spotify servers where SpotX grabs them. The same is true for SpotX-Bash and the macOS releases.

Spotify only hosts the current stable and experimental versions of Spotify for Linux so therefore those are the only options available in SpotX-Bash. We will never use a 3rd party file host to pull files from. Users are free to download and install older versions or the app from other sources and then patch with SpotX-Bash.
