### ISSUE TITLE
SpotX not installing, stating "no backup file!"

### ISSUE THREAD

**Issue by breddie-normie** [SpotX-Official/SpotX-Bash#21]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have read the FAQ
- [X] I have checked previous issues, open and closed
- [X] I have re-installed Spotify and the issue is not present on stock but returns after re-applying SpotX-Bash

### Сountry of your account

India

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify version: 1.2.22.982
- OS: Artix Linux
- Shell: fish  (switched to bash for installation)
```

### 📝 Description

Tried reinstalling both spotify-launcher and this program, but to no avail.

### 🖥️ Terminal Input/Output

 bash <(curl -sSL https://spotx-official.github.io/run.sh) -cdhf

████╗███╗  ███╗ █████╗█╗  █╗  ███╗  ██╗ ████╗█╗ █╗
█╔══╝█╔═█╗█╔══█╗╚═█╔═╝╚█╗█╔╝  █╔═█╗█╔═█╗█╔══╝█║ █║
████╗███╔╝█║  █║  █║   ╚█╔╝██╗███╔╝████║████╗████║
╚══█║█╔═╝ █║  █║  █║   █╔█╗╚═╝█╔═█╗█╔═█║╚══█║█╔═█║
████║█║   ╚███╔╝  █║  █╔╝ █╗  ███╔╝█║ █║████║█║ █║
╚═══╝╚╝    ╚══╝   ╚╝  ╚╝  ╚╝  ╚══╝ ╚╝ ╚╝╚═══╝╚╝ ╚╝

Searching for Spotify directory...

Found Spotify Directory: /home/breddie/.local/share/spotify-launcher/install/usr/share/spotify

/home/breddie/.local/share/spotify-launcher/install/usr/share/spotify/spotify: /usr/lib/libcurl-gnutls.so.4: no version information available (required by /home/breddie/.local/share/spotify-launcher/install/usr/share/spotify/spotify)
Latest supported version: 1.2.22.982
Detected Spotify version: 1.2.22.982

✔ Created backup
✔ Cleared app cache

Warning: Detected SpotX but no backup file! Reinstall Spotify. Exiting...

### 📸 Screenshots

![image](https://github.com/SpotX-Official/SpotX-Bash/assets/127048853/8137622c-1792-47b6-835c-2c40b84499c9)

**Comment by jetfir3** [comment]
Hmm.. something strange is going on as it's detecting modified files even before any patches were made. 

I would suggest uninstalling Spotify again and also deleting your Spotify directory:
```
rm -rf /home/breddie/.local/share/spotify-launcher/install/usr/share/spotify/
```

then re-installing Spotify however you install it.. then re-running SpotX-Bash with the following:
```
bash <(curl -sSL https://spotx-official.github.io/run.sh) -dh
```

And share the results from all of that. 
I do not know how spotify-launcher works exactly when it moves files around during installation. So if you had previously patched Spotify with SpotX-Bash.. then updated Spotify with spotify-launcher.. then tried re-patching with SpotX-Bash.. something weird could have happened.

**Comment by jetfir3** [comment]
Closed due to no response after 1 week. 

Previous post should take care of specific issue.

**Comment by breddie-normie** [comment]
> Closed due to no response after 1 week.
> 
> Previous post should take care of specific issue.

Sorry for this late reply, it's now working properly. Thanks for resolving this. Cheers.
