### ISSUE TITLE
Lyrics button disappears after installation

### ISSUE THREAD

**Issue by buddyjojo** [SpotX-Official/SpotX-Bash#22]
As title states, the lyrics button disappears entirely after installation but comes back after uninstalling Spotx with --uninstall
Tried installing without experimental features but same thing happened.

Spotify version is 1.2.22.982 running on Debian 12.

**Comment by jetfir3** [comment]
Lyrics moves into the new right sidebar on songs that support lyrics. 

it shows up as a button when you uninstall because the new change has not been pushed to your account yet (spotx enables this change). 

and don't skip the bug template next time.

**Comment by buddyjojo** [comment]
Ah I see. 
The bug template was just asking for too much mandatory options that was unnecessary for this simple question.
