### ISSUE TITLE
There is no input parameter listed in SpotXBash equivalent to the new -EnhancedSongs parameter in SpotX-Official

### ISSUE THREAD

**Issue by lonskyne** [SpotX-Official/SpotX-Bash#23]
SpotX-Official recently removed (as default) the experimental feature that adds the Enhance button. Now you need to pass the -EnhancedSongs parameter, but in SpotX-Bash there is no equivalent.

**Comment by jetfir3** [comment]
SpotX-Bash is not SpotX. Smart Shuffle has officially replaced the Enhance button and SpotX-Bash is doing the same.

Before 1.2.22.982 has Enhance button. 1.2.22.982 and after has Smart Shuffle.

Or choose your experimental features using the Remote Config option in developer mode's debug window. All users have complete control of every single experimental feature enabled/disabled this way.

**Comment by jetfir3** [comment]
Looks like Spotify will be removing the Enhance experimental feature completely in v1.2.26.x.
Anyone wanting to use Enhance instead of Smart Shuffle will have to use v1.2.25.x or earlier.
