### ISSUE TITLE
Can't specify spotify directory

### ISSUE THREAD

**Issue by vuthanho** [SpotX-Official/SpotX-Bash#25]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have read the FAQ
- [X] I have checked previous issues, open and closed
- [X] I have completed all troubleshooting steps and the issue is not present on stock but returns after re-applying SpotX-Bash

### Сountry of your account

Belgium

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify version: Spotify version 1.2.25.1011.g0348b2ea
- OS: Pop!_OS 22.04 LTS x86_64
- Shell: zsh 5.8.1
```

### 📝 Description

1. Specify a path with `-P`
...

### 🖥️ Terminal Input/Output

❯ bash <(curl -sSL https://spotx-official.github.io/run.sh)

Searching for Spotify directory...

Error: Spotify directory not found.
Set directory path with '-P' flag.

❯ bash <(curl -sSL https://spotx-official.github.io/run.sh) -P /usr/share/spotify

Error: Spotify not found in path set by '-P'.
Confirm directory and try again.

❯ ll /usr/share/spotify
total 265M
drwx------ 5 xxx  xxx  4,0K déc.   1 14:54 Apps
drwxr-xr-x 2 root root 4,0K déc.   1 14:31 apt-keys
-rw-rw-r-- 1 root root 641K nov.   8 07:47 chrome_100_percent.pak
-rw-rw-r-- 1 root root 993K nov.   8 07:47 chrome_200_percent.pak
drwxr-xr-x 2 root root 4,0K déc.   1 14:31 icons
-rw-rw-r-- 1 root root  11M nov.   8 06:28 icudtl.dat
-rw-rw-r-- 1 root root 198M nov.  20 17:56 libcef.so
-rw-rw-r-- 1 root root 253K nov.  20 17:56 libEGL.so
-rw-rw-r-- 1 root root 6,2M nov.  20 17:56 libGLESv2.so
-rw-rw-r-- 1 root root 3,9M nov.  20 17:56 libvk_swiftshader.so
-rw-rw-r-- 1 root root 604K nov.  20 17:56 libvulkan.so.1
drwxr-xr-x 2 root root 4,0K déc.   1 14:31 locales
-rw-rw-r-- 1 root root 7,8M nov.   8 09:29 resources.pak
-rw-rw-r-- 1 root root 270K nov.   8 08:07 snapshot_blob.bin
-rwxr-xr-x 1 root root  36M nov.  20 17:56 spotify
-rw-r--r-- 1 root root  238 nov.  20 17:47 spotify.desktop
-rw-rw-r-- 1 root root 623K nov.   8 09:36 v8_context_snapshot.bin
-rw-rw-r-- 1 root root  107 nov.   8 07:45 vk_swiftshader_icd.json

**Comment by jetfir3** [comment]
It's strange that both auto search and -P are failing. 

Can you list what's in /usr/share/spotify/Apps/ ?

**Comment by vuthanho** [comment]
Here you are
```
ls -l /usr/share/spotify/Apps/
total 11096
-rwx------ 1 xxx xxx 2736167 déc.   1 15:27 login.spa
-rwx------ 1 xxx xxx 8619731 déc.   1 15:27 xpui.spa
```

**Comment by vuthanho** [comment]
For some weird reason, it is now working... I haven't touched spotify since then though. And I don't see any recent commit related to that, so I guess it was from my side. Maybe rebooting did something.

**Comment by jetfir3** [comment]
Your output of `ls -l /usr/share/spotify/Apps/` doesn't seem to match what your original ll output of `/usr/share/spotify/` suggested... which was multiple subdirectories and a timestamp that differed from all other timestamps in the spotify directory which would mean it was edited at some point after the initial install. 

Not sure if you had Spicetify installed at some point.. or had touched the ./Apps dir yourself along the way but maybe a reboot and reinstall or something cleared things up, bringing Spotify dir back to proper untouched stock allowing the patch to work as expected.

**Comment by SatyaDewangan05** [comment]
use this
```
bash <(curl -sSL https://spotx-official.github.io/run.sh) --installdeb
```
the -P is only needed if you've already installed the official Spotify.
