### ISSUE TITLE
segfault on 1.2.31.1205 (linux)

### ISSUE THREAD

**Issue by k1gen** [SpotX-Official/SpotX-Bash#33]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have read the FAQ
- [X] I have checked previous issues, open and closed
- [X] I have completed all troubleshooting steps and the issue is not present on stock but returns after re-applying SpotX-Bash

### Сountry of your account

Poland

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify version: 1.2.31.1205
- OS: Arch Linux
- Shell: zsh
```

### 📝 Description

1. install spotify with aur
2. run spotify (runs fine)
3. run `bash <(curl -sSL https://spotx-official.github.io/run.sh) -cfhl -P /opt/spotify`
4. run spotify and get
```
User flags: --enable-features=UseOzonePlatform --ozone-platform=wayland
/opt/spotify/spotify: /usr/lib/libcurl-gnutls.so.4: no version information available (required by /opt/spotify/spotify)
zsh: segmentation fault (core dumped)  /usr/bin/spotify
```
(same without userflags, .cache/spotify & .config/spotify don't exist)

### 🖥️ Terminal Input/Output

```
❯ bash <(curl -sSL https://spotx-official.github.io/run.sh) -cfhl -P /opt/spotify

████╗███╗  ███╗ █████╗█╗  █╗  ███╗  ██╗ ████╗█╗ █╗
█╔══╝█╔═█╗█╔══█╗╚═█╔═╝╚█╗█╔╝  █╔═█╗█╔═█╗█╔══╝█║ █║
████╗███╔╝█║  █║  █║   ╚█╔╝██╗███╔╝████║████╗████║
╚══█║█╔═╝ █║  █║  █║   █╔█╗╚═╝█╔═█╗█╔═█║╚══█║█╔═█║
████║█║   ╚███╔╝  █║  █╔╝ █╗  ███╔╝█║ █║████║█║ █║
╚═══╝╚╝    ╚══╝   ╚╝  ╚╝  ╚╝  ╚══╝ ╚╝ ╚╝╚═══╝╚╝ ╚╝

Using Spotify Directory: /opt/spotify

Latest supported version: 1.2.31.1205
Detected Spotify version: 1.2.31.1205

✔ Cleared app cache
✔ Detected & restored backup
✔ Applied free-tier plan patches
✔ Enabled experimental features
✔ Removed non-music categories on home screen
✔ Removed lyrics background color
✔ Finished
```

**Comment by bytedream** [comment]
Uninstalling (and removing the `/opt/spotify` directory completely, idk if this was necessary) and then installing it again resolved the issue for me

**Comment by jetfir3** [comment]
@bytedream @k1gen 

glad the clean install got things going. To be honest, I'm not sure why this happens... I don't use arch regularly enough to trigger the issue. 

did either of you happen to test if `1.2.31.1205` worked prior to patching with SpotX-Bash (or run the SpotX-Bash `--uninstall` option to reverse the changes it made and then test the client)? I'm curious if the update path itself would have caused this somehow and it was unrelated to the patching or if it was indeed triggered by SpotX-Bash. 

Not asking either of you to recreate the scene but if something like this happens again or anyone else out there who is reading this... and it's confirmed that the same client version worked prior to patching with SpotX-Bash (or works again after running SpotX-Bash `--uninstall` option)...

I would be interested to see the `/opt/spotify` directory when this happens. `ls -la` output and hashes of all the files to see if something can be narrowed down. Or even better, compressing the directory and uploading it to some 3rd party file host so the contents could be inspected. 

It doesn't make much sense that SpotX-Bash could be causing this and yet a clean reinstall + patch works without issue. But... can't rule it out entirely. I do see lots of "segmentation fault" reports from regular Spotify users on arch after upgrading (no SpotX-Bash involved).

**Comment by k1gen** [comment]
yeah, I noticed the script was taking a long time to detect the installation after upgrading from 1.2.26.1187 to 1.2.31.1205. if I clean-upgrade - this disappears, and there is no such problem now

**Comment by jetfir3** [comment]
> yeah, I noticed the script was taking a long time to detect the installation after upgrading from 1.2.26.1187 to 1.2.31.1205. if I clean-upgrade - this disappears, and there is no such problem now

See my previous comment edit.. I was in process of rewriting it when you commented. Not sure how to best handle this.. but at least it's now noted what's going on and how to workaround it for now.

**Comment by k1gen** [comment]
thank you for your research on this matter and your great work on SpotX-Bash overall, @jetfir3!

**Comment by jetfir3** [comment]
I've corrected this issue. 

The user should now be able to use SpotX-Bash normally without having to consider Spotify updates or existing backup files.
