### ISSUE TITLE
Warning: Detected SpotX-Bash but no backup file! Reinstall Spotify. Exiting...

### ISSUE THREAD

**Issue by Fandyfr** [SpotX-Official/SpotX-Bash#34]
### 🧐 Have you fully read the README and viewed similar issues?

- [x] I have read the README
- [X] I have read the FAQ
- [X] I have checked previous issues, open and closed
- [X] I have completed all troubleshooting steps and the issue is not present on stock but returns after re-applying SpotX-Bash

### Сountry of your account

Indonesia

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify version: 1.2.31.1205
- OS: Ubuntu
- Shell: Teriminal
```

### 📝 Description

How to Patch non Backup? Force Patch

### 🖥️ Terminal Input/Output

Searching for Spotify directory...

Found Spotify Directory: /usr/share/spotify

Latest supported version: 1.2.31.1205
Detected Spotify version: 1.2.31.1205

✔ Created backup

Warning: Detected SpotX-Bash but no backup file! Reinstall Spotify. Exiting...

### 📸 Screenshots

![image](https://github.com/SpotX-Official/SpotX-Bash/assets/135007919/94e105e4-8b4c-4eea-b1ef-e42ee3396b06)

**Comment by jetfir3** [comment]
Odd... not sure what's going on with your Spotify directory. You also did not share the exact command you used. 
Did you just run the following command.. no additional flags?
```
bash <(curl -sSL https://spotx-official.github.io/run.sh)
```

I would suggest trying the following two commands and see if these work. 
1. 
```
sudo rm -rf /usr/share/spotify/
```
2.
```
bash <(curl -sSL https://spotx-official.github.io/run.sh) --installdeb
```

Are there any errors or issues with those commands? If no, great.. if yes, please share screenshots of both the command you entered into terminal and any script output... and also please share the output of `ls -l /usr/share/spotify/`
