### ISSUE TITLE
Getting key not found error

### ISSUE THREAD

**Issue by kadattack** [SpotX-Official/SpotX-Bash#35]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have read the FAQ
- [X] I have checked previous issues, open and closed
- [X] I have completed all troubleshooting steps and the issue is not present on stock but returns after re-applying SpotX-Bash

### Сountry of your account

Croatia

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify version: 1.2.31.1205.g4d59ad7c
- OS: Pop_os 22.04 TLS
- Shell: bash
```

### 📝 Description

1. Run app
2. Go to a The Joe Rogan Experience podcast
3.  Click on the green play button on any of the episodes

The result is the app craches

I've tried some other podcasts and i've tried other music and they work without any issues.

### 🖥️ Terminal Input/Output

> $ flatpak run com.spotify.Client
> /app/extra/bin/spotify: /usr/lib/x86_64-linux-gnu/libcurl.so.4: no version information available (required by /app/extra/bin/spotify)
> [spotifywm] attached to spotify
> /app/extra/share/spotify/spotify: /usr/lib/x86_64-linux-gnu/libcurl.so.4: no version information available (required by /app/extra/share/spotify/spotify)
> /app/extra/share/spotify/spotify: /usr/lib/x86_64-linux-gnu/libcurl.so.4: no version information available (required by /app/extra/share/spotify/spotify)
> [spotifywm] attached to spotify
> [spotifywm] attached to spotify
> Gtk-Message: 19:49:51.445: Failed to load module "canberra-gtk-module"
> Gtk-Message: 19:49:51.446: Failed to load module "canberra-gtk-module"
> [spotifywm] spotify window 3a00004 found
> /proc/self/exe: /usr/lib/x86_64-linux-gnu/libcurl.so.4: no version information available (required by /proc/self/exe)
> [spotifywm] spotify window 3800003 found
> [spotifywm] attached to spotify
> [spotifywm] spotify window 4200004 found

After pressing the green play button on the podcast episode it shows this in the terminal and shuts down

> libc++abi: terminating with uncaught exception of type std::out_of_range: unordered_map::at: key not found

**Comment by osalyousef** [comment]
it might be an issue with spotify itself , not the spotX patch .. 

> Failed to load module "canberra-gtk-module" 
might be your problem 

please check this [link](Failed to load module "https://www.tecmint.com/failed-to-load-module-canberra-gtk-module/")

**Comment by kadattack** [comment]
I followed the instructions and it says that `libcanberra-gtk-module is already the newest version (0.30-10ubuntu1.22.04.1).`

The episodes worked before using the spotX script. 

However I do have an alternative way of viewing the episodes by pressing `Share > Embed episode` and it plays fine.

**Comment by jetfir3** [comment]
> The episodes worked before using the spotX script.

Can you re-run the SpotX-Bash command with the `-f` flag to force a re-patch and let me know if you are still seeing the `key not found` error?

**Comment by kadattack** [comment]
Yeah still seeing it. I even tried un-intalling Spotify and reinstalling it and the gtk-module failure to load happens even in nonpatched version and doesn't cause issues. If i run the script it breaks it again.

**Comment by jetfir3** [comment]
> Yeah still seeing it. I even tried un-intalling Spotify and reinstalling it and the gtk-module failure to load happens even in nonpatched version and doesn't cause issues. If i run the script it breaks it again. Also tried the -c command for cache clearing and doesn't help.

Gotcha. Thanks for testing. Seems I'll have to completely remove the podcast adblock-related patches for the Linux client. No issues on the Windows/macOS side (in my testing) but I was able to replicate on Linux. My previous edit allowed it to work, though not working for you -- so completely disabling it (for now). 

Running the SpotX-Bash command with `-f` should revert previous patches and re-patch with latest changes.

**Comment by jetfir3** [comment]
> it actually fixed the issue. Nice one!

Ooo, you downloaded it.. I see. Downloaded/local scripts are almost always outdated as things are constantly updated. 

But good to know the previous edit did end up working... so I'll revert the latest edit and see how that goes for now.

**Comment by jetfir3** [comment]
> Edit: But from what i can see the video is no longer playing? Well at least the audio works.

Just saw your latest edit... didn't see that until I posted my previous comment.  

When you get a chance can you test both and let me know which gets podcast video to return? (if neither do, then it would seem unrelated to the patches)

test 1:
https://github.com/SpotX-Official/SpotX-Bash/blob/8f9bb752e05c1d57e01d6fcb7cc6bfadb785f941/spotx.sh

test 2:
https://github.com/SpotX-Official/SpotX-Bash/blob/42e3327ecd47719d0c4b412d493996b6a1f32d6c/spotx.sh

**Comment by kadattack** [comment]
Yeah that was my f-up. While i was testing why the podcasts don't work i decided to download one to see maybe if that would work and it turns out it only downloads the audio, so if you play it no video shows up. 
Sorry about that, it works now. You can close the issue.
