### ISSUE TITLE
Feature request: don't require write permissions

### ISSUE THREAD

**Issue by JohnFinn** [SpotX-Official/SpotX-Bash#38]
I guess instead of performing write operations on files, we could simply copy them and perform write operations on copies instead. This would enable the program to not require root access.

I believe the feature won't introduce any disk space overhead. (had a quick look at the code and there is already copy mechanism for backup and later uninstallation)

Also uninstallation process will potentially get simpler as it won't require any operations on the files we wrote something to.

**Comment by jetfir3** [comment]
So you want the script to make a 1:1 copy of the entire Spotify app into a user-writable directory and then patch that instead? And then the user would run the Spotify installation from the new user directory location instead of the default location?

Or am I not understanding?

**Comment by JohnFinn** [comment]
Yes, that's what I meant

**Comment by jetfir3** [comment]
The original intention of the script is to patch the stock Spotify client in its default location.

If a user doesn't want to grant write access to the default Spotify directories, the user could make their own copy of the Spotify app into a directory of their choice then point the script to that directory instead of the default locations, using the `-P [path]` option. 

Would this not essentially do what you want?

```
cp -r $spotifyDirectory $HOME/$spotifyDirectory
spotX.sh -P $HOME/$spotifyDirectory
```

**Comment by JohnFinn** [comment]
Works, thanks

**Comment by JohnFinn** [comment]
Just discovered that in this setup if I delete the original `spotify` installation, the copy stops working

**Comment by jetfir3** [comment]
> Just discovered that in this setup if I delete the original `spotify` installation, the copy stops working

this doesn't seem like standard behavior, perhaps it may depend on your distro and Spotify setup. 

Debian, Ubuntu and any APT-based distro with installs via official DEB do not require Spotify in it's default location. 
Arch (and Arch-based distros) using spotify-launcher already has the client installed into $HOME.
macOS can run the Spotify.app from any directory the user has access to.

I don't flatpak so can't speak on that.

**Comment by JohnFinn** [comment]
> this doesn't seem like standard behavior, perhaps it may depend on your distro and Spotify setup.

I think so too. I use nixos, and it does a lot of stuff to isolate packages

**Comment by jetfir3** [comment]
> I use nixos, and it does a lot of stuff to isolate packages

Hmm, I see. Not familiar with nixos (just had to Google it). Seems that "easy-mode" would be to leave the original install in-place and deal with the loss of the additional ~200MB of space required for the original + copy (assuming the spotx-patched copy did indeed work after testing). 

Just curious...
What's the default install path for the Spotify client on nixos (specifically, where is xpui.spa located)?
Is writing to the default install directory possible when write-permission is given? 

I know SpotX-Bash works for both system and user-installed flatpaks but if the installs are more like "snaps" which creat read-only containers which are mounted then obviously modifying those directories would not be possible without first unpacking.

**Comment by oskardotglobal** [comment]
A very dirty fix for this problem:
You can override the installation script inside the spotify nix package to call the spotx installation script just before the postinstall hook. This is not really the nix way, but it seems to work.

In your `configuration.nix`:
```nix
nixpkgs.overlays = [
  (final: prev: {
    spotify =
      prev.spotify
      // {
        installPhase =
          builtins.replaceStrings [
            "runHook postInstall"
            ''
              bash <(curl -sSL https://spotx-official.github.io/run.sh) -P "$out/share/spotify"
              runHook postInstall
            ''
          ]
          prev.spotify.installPhase;
      };
  })
];
```

**Comment by oskardotglobal** [comment]
Yeah sorry, that overlay is outdated. Now, I am using a modified spotify package which you can find [here in my .dotfiles](https://github.com/oskardotglobal/.dotfiles/tree/nix/packages/spotify) and then overlay in my flake [here](https://github.com/oskardotglobal/.dotfiles/blob/nix/flake.nix#L39). Just copy the package files into your config and you'll be good to go

**Comment by oskardotglobal** [comment]
Yes, exactly. Copy the packages/spotify folder into your config and then add the overlay. Since you're probably not using a flake, add
```nix
nixpkgs.overlays = [
  (final: prev: {
    spotify = prev.callPackage ./packages/spotify {};
  })
];
```
to your configuration.nix.
Then, just normally add `spotify` to your `environment.systemPackages`

**Comment by oskardotglobal** [comment]
You have to change the hash every time you rebuild in packages/spotify/linux.nix.patch and then run update.sh, the installation script is not pinned to a specific version

**Comment by oskardotglobal** [comment]
This is really unrelated here. See the readme on my dotfiles repo, open an issue there if you need help.
