### ISSUE TITLE
[Linux] Spotify installation not found. (arch)

### ISSUE THREAD

**Issue by Helikopter863** [SpotX-Official/SpotX-Bash#39]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have read the FAQ
- [X] I have checked previous issues, open and closed
- [X] I have completed all troubleshooting steps and the issue is not present on stock but returns after re-applying SpotX-Bash

### Сountry of your account

Poland

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify version: 1:1.2.31.1205-2 (latest from aur)
- OS: arch linux 
- Shell: bash
```

### 📝 Description

so the script says that spotify isn't in the /opt/spotify path, even though it is there. i used the script like 2/3 hours ago, and it worked just fine with the same OS etc. apprarently some of the changes broke it. i've already tried rebooting, setting the path via -P and so on, but nothing worked.

### 🖥️ Terminal Input/Output

Error: Spotify installation not found.
Install Spotify or set Spotify directory path with '-P' flag.

### 📸 Screenshots

![image](https://github.com/SpotX-Official/SpotX-Bash/assets/159429130/448fdd04-bf8e-41b4-85f6-0c2dae2b148b)

**Comment by jetfir3** [comment]
This should be sorted now. Was an issue with the case of the path.

Running the command again will work as long as you're not pulling a cached page.
