### ISSUE TITLE
Show Lyrics button nowhere to be found

### ISSUE THREAD

**Issue by jajooo** [SpotX-Official/SpotX-Bash#40]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have read the FAQ
- [X] I have checked previous issues, open and closed
- [X] I have completed all troubleshooting steps and the issue is not present on stock but returns after re-applying SpotX-Bash

### Сountry of your account

Slovakia

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify version: 1.2.31.1205
- OS: Arch Linux 6.8.8
- Shell: Bash
```

### 📝 Description

1. Install using bash <(curl -sSL https://spotx-official.github.io/run.sh) -c -f
2. Launch Spotify
3. Look for "Show Lyrics" button
...

### 🖥️ Terminal Input/Output

bash <(curl -sSL https://spotx-official.github.io/run.sh) -c -f

████╗███╗  ███╗ █████╗█╗  █╗  ███╗  ██╗ ████╗█╗ █╗
█╔══╝█╔═█╗█╔══█╗╚═█╔═╝╚█╗█╔╝  █╔═█╗█╔═█╗█╔══╝█║ █║
████╗███╔╝█║  █║  █║   ╚█╔╝██╗███╔╝████║████╗████║
╚══█║█╔═╝ █║  █║  █║   █╔█╗╚═╝█╔═█╗█╔═█║╚══█║█╔═█║
████║█║   ╚███╔╝  █║  █╔╝ █╗  ███╔╝█║ █║████║█║ █║
╚═══╝╚╝    ╚══╝   ╚╝  ╚╝  ╚╝  ╚══╝ ╚╝ ╚╝╚═══╝╚╝ ╚╝

Searching for Spotify directory...

Found Spotify Directory: /opt/spotify

Latest supported version: 1.2.36.959
Detected Spotify version: 1.2.31.1205

✔ Cleared app cache
✔ Detected & restored backup
✔ Applied free-tier plan patches
✔ Enabled experimental features
✔ Finished

### 📸 Screenshots

![image](https://github.com/SpotX-Official/SpotX-Bash/assets/93209510/be9baa52-cfb6-4fba-b17a-d4737ccf6f6e)

**Comment by jetfir3** [comment]
So based on your bug report, you have full working lyrics when you uninstall SpotX-Bash?

**Comment by jajooo** [comment]
That's right

**Comment by jetfir3** [comment]
Please share screenshot... but you may be the last free-tier user that has working lyrics as Spotify now requires premium plan for lyrics support as of May 1, 2024.

**Comment by jajooo** [comment]
![image](https://github.com/SpotX-Official/SpotX-Bash/assets/93209510/f267fe0c-c827-49bc-96a1-f036e3405d55)

Without SpotX-Bash

The lyrics button is now at the bottom, but it does not load lyrics

**Comment by jetfir3** [comment]
It's not your wifi. As mentioned, Spotify has removed lyrics for all free-tier users and now requires Premium. 

Client version 1.3.36+ is required to view 3 songs per month and this client version is not yet available on Linux. But with only 3 songs per month available without paying, it becomes worthless.. as it's just there to remind you to pay for premium if you want them.

If you want your broken lyrics button to return while using SpotX-Bash, you can:
- enable developer mode while installing (`-d` / `--devmode`)
- open Spotify, click on your user icon and select `debug window` from the dropdown
- navigate to `Remote Config` in the new window that opens
- set `enableRightSidebarLyrics` to false

**Comment by jajooo** [comment]
Okay, Thanks!

**Comment by jetfir3** [comment]
As of July 30, 2024 Spotify has started to return full/synced lyrics for free tier members. 

Since we last checked, lyrics should be available to most users running desktop client version v1.2.36.955 or higher. It's likely this will expand to some older version numbers in the future but currently  too soon to say. Lyrics availability seems to be rolling out to accounts and is not based on region. If you do not yet have lyrics on v1.2.36.955 or higher, hopefully you will get them back soon.

**Comment by mightbesimon** [comment]
> It's not your wifi. As mentioned, Spotify has removed lyrics for all free-tier users and now requires Premium.
> 
> Client version 1.3.36+ is required to view 3 songs per month and this client version is not yet available on Linux. But with only 3 songs per month available without paying, it becomes worthless.. as it's just there to remind you to pay for premium if you want them.
> 
> If you want your broken lyrics button to return while using SpotX-Bash, you can:
> 
> * enable developer mode while installing (`-d` / `--devmode`)
> * open Spotify, click on your user icon and select `debug window` from the dropdown
> * navigate to `Remote Config` in the new window that opens
> * set `enableRightSidebarLyrics` to false

for 1.2.58, this actually works and yields a working lyrics button!

Spotify for macOS (Apple Silicon)
1.2.58.498.g6afe77b7
xpui_2025-02-24_1740386752460_6afe77b
cef_131.3.1+gcb062df+chromium-131.0.6778.109
Runtime: Chrome
Build System: Bazel
