### ISSUE TITLE
Obfuscated/encoded strings?

### ISSUE THREAD

**Issue by crwn1337** [SpotX-Official/SpotX-Bash#43]
Is there any reason for why a lot of the variables use encoded strings? I know these can be easily decoded but what's the purpose?

Examples:
https://github.com/SpotX-Official/SpotX-Bash/blob/82a390ef9b35400098e2be633c0301dff3ff3167/spotx.sh#L99
https://github.com/SpotX-Official/SpotX-Bash/blob/82a390ef9b35400098e2be633c0301dff3ff3167/spotx.sh#L102
https://github.com/SpotX-Official/SpotX-Bash/blob/82a390ef9b35400098e2be633c0301dff3ff3167/spotx.sh#L211
https://github.com/SpotX-Official/SpotX-Bash/blob/82a390ef9b35400098e2be633c0301dff3ff3167/spotx.sh#L248
https://github.com/SpotX-Official/SpotX-Bash/blob/82a390ef9b35400098e2be633c0301dff3ff3167/spotx.sh#L250-L251
https://github.com/SpotX-Official/SpotX-Bash/blob/82a390ef9b35400098e2be633c0301dff3ff3167/spotx.sh#L492-L493
https://github.com/SpotX-Official/SpotX-Bash/blob/82a390ef9b35400098e2be633c0301dff3ff3167/spotx.sh#L521-L522

**Comment by jetfir3** [comment]
avoiding various terms which may hit search engines etc. obviously nothing to hide for anyone who's curious since, as you mentioned, they can be immediately decoded.

**Comment by crwn1337** [comment]
> avoiding various terms which may hit search engines

The readme has a full on plain text "Adblock for the Spotify desktop client", so which types of terms is it specifically avoiding?


> obviously nothing to hide for anyone who's curious

Sure, but looking through every commit and decoding (if added) can get troublesome.

**Comment by jetfir3** [comment]
> which types of terms is it specifically avoiding?

Literally the things which are encoded.

**Comment by amd64fox** [comment]
> Sure, but looking through every commit and decoding (if added) can get troublesome.

if this is just a one-time code check on your part, then I don’t think it will take you much time to decode these few lines, if you have a different reason, then I suggest you tell me more about it
