### ISSUE TITLE
Not Blocking Commercials on Spotify for macOS (Apple Silicon) 1.2.38.720.ga4a70a0e

### ISSUE THREAD

**Issue by 5uck3rpunch** [SpotX-Official/SpotX-Bash#44]
I love this hack. I just updated to Spotify for macOS (Apple Silicon) 1.2.38.720.ga4a70a0e this morning & reinstalled the hack. The ads are not shown in Spotify, but I still get the audio commercials in a certain time frame. Hopefully you will find the fix soon. Thank you for all of your hard work!

**Comment by jetfir3** [comment]
this is not how you submit an Issue. File out the bug template and provide all information and be as detailed as possible. 

The script is working perfectly fine, so there is an issue with something on your end.. so details matter.

**Comment by 5uck3rpunch** [comment]
Will do and sorry.
