### ISSUE TITLE
Can´t install SpotX-bash

### ISSUE THREAD

**Issue by ImxTreme21** [SpotX-Official/SpotX-Bash#45]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have read the FAQ
- [X] I have checked previous issues, open and closed
- [X] I have completed all troubleshooting steps and the issue is not present on stock but returns after re-applying SpotX-Bash

### Сountry of your account

Perú

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

Yes

### ℹ Computer information

```markdown
- Spotify version: spotify 1:1.2.37.701-1 (AUR)
- OS: EndeavourOS (Arch Linux basically) kernel Linux 6.9.2-zen1-1-zen
- Shell: /usr/bin/zsh
```

### 📝 Description

1. Copy and paste command from readme into terminal
2. Press enter, it doesnt work.

### 🖥️ Terminal Input/Output

❯ bash <(curl -sSL https://spotx-official.github.io/run.sh) -eh -P /opt/spotify/

████╗███╗  ███╗ █████╗█╗  █╗  ███╗  ██╗ ████╗█╗ █╗
█╔══╝█╔═█╗█╔══█╗╚═█╔═╝╚█╗█╔╝  █╔═█╗█╔═█╗█╔══╝█║ █║
████╗███╔╝█║  █║  █║   ╚█╔╝██╗███╔╝████║████╗████║
╚══█║█╔═╝ █║  █║  █║   █╔█╗╚═╝█╔═█╗█╔═█║╚══█║█╔═█║
████║█║   ╚███╔╝  █║  █╔╝ █╗  ███╔╝█║ █║████║█║ █║
╚═══╝╚╝    ╚══╝   ╚╝  ╚╝  ╚╝  ╚══╝ ╚╝ ╚╝╚═══╝╚╝ ╚╝

Error: Spotify not found in path set by '-P'.
Confirm directory and try again.

~ ❯ 

Spotify is indeed installed in opt/spotify/ idk wtf is going on.

**Comment by jetfir3** [comment]
You've selected that you have Spicetify installed. If this is true then that explains the issue... Spicetify changes directory integrity so the script is unable to work properly. 

The FAQ covers this and mentions that if Spicetify is to be used it must be run AFTER running SpotX-Bash.
1. Fresh install of Spotify
2. Run SpotX-Bash
3. Run Spceitfy

if you do NOT have Spicetify installed and filled out this form incorrectly then the next thing we can look at is directory structure... provide the output from each command:
```
ls -la /opt/spotify/
```
```
ls -la /opt/spotify/Apps/
```

**Comment by ImxTreme21** [comment]
Ty, it works now.
