### ISSUE TITLE
Ampersand in a string is causing experimental features to not be installed properly

### ISSUE THREAD

**Issue by CrystalFyre** [SpotX-Official/SpotX-Bash#46]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have read the FAQ
- [X] I have checked previous issues, open and closed
- [X] I have completed all troubleshooting steps and the issue is not present on stock but returns after re-applying SpotX-Bash

### Сountry of your account

Canada

### What is your Spotify Plan?

Premium

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify version: 1.2.8.923
- OS: Linux Mint 21.3 Cinnamon
- Shell: bash
```

### 📝 Description

1. Ran the installer, run.sh, which in turn ran the spotx.sh bash file (With or without options or arguments)
2. ???
3. And you're done!
...

There's an unintended ampersand `&` in the middle of a string used for the experimental features Array, `expEx`. Specifically, on `line 865`.
Change it to the word 'and', and the script will run fine.

### 🖥️ Terminal Input/Output

```
Searching for Spotify directory...

Found Spotify Directory: /usr/share/spotify

cat: /etc/upstream-release: Is a directory
Debug: Linux Mint 21.3
Debug: x86_64 detected
Debug: APT detected
Debug: flatpak detected
Debug: Cache directory: ~/.cache/spotify

Latest supported version: 1.2.39.578
Detected Spotify version: 1.2.8.923

✔ Created backup
✔ Applied free-tier plan patches
Unquoted string "web" may clash with future reserved word at -e line 1.
String found where operator expected at -e line 1, near "web",default:\K!1}"
Unknown regexp modifier "/t" at -e line 1, near "+= "
Can't find string terminator '"' anywhere before EOF at -e line 1.
✔ Enabled experimental features
✔ Enabled new UI
✔ Finished

```

### 📸 Screenshots

![image](https://github.com/SpotX-Official/SpotX-Bash/assets/55814059/0c215894-8fd1-471b-8019-90f34344c4ad)

**Comment by jetfir3** [comment]
Sorry about that. Good catch. Fixed.
