### ISSUE TITLE
Spotify installation not found

### ISSUE THREAD

**Issue by Dizobo** [SpotX-Official/SpotX-Bash#47]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have read the FAQ
- [X] I have checked previous issues, open and closed
- [X] I have completed all troubleshooting steps and the issue is not present on stock but returns after re-applying SpotX-Bash

### Сountry of your account

United States

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify version: Spotify Flatpak 1.2.37.701.ge66eb7bc
- OS: Fedora 40
- Shell: zsh (I have tried bash as well)
```

### 📝 Description

1. Run Install Script `bash <(curl -sSL https://raw.githubusercontent.com/SpotX-Official/SpotX-Bash/main/spotx.sh)`
2. Error: Spotify installation not found.
3. Error: Spotify not found in path set by '-P'.

I noticed that https://github.com/SpotX-Official/SpotX-Bash/commit/05db02ec9eaf341544ff6e51163159678c1404ea detects the installation correctly. I have not tested any commits after that. 
...

### 🖥️ Terminal Input/Output

████╗███╗  ███╗ █████╗█╗  █╗  ███╗  ██╗ ████╗█╗ █╗
█╔══╝█╔═█╗█╔══█╗╚═█╔═╝╚█╗█╔╝  █╔═█╗█╔═█╗█╔══╝█║ █║
████╗███╔╝█║  █║  █║   ╚█╔╝██╗███╔╝████║████╗████║
╚══█║█╔═╝ █║  █║  █║   █╔█╗╚═╝█╔═█╗█╔═█║╚══█║█╔═█║
████║█║   ╚███╔╝  █║  █╔╝ █╗  ███╔╝█║ █║████║█║ █║
╚═══╝╚╝    ╚══╝   ╚╝  ╚╝  ╚╝  ╚══╝ ╚╝ ╚╝╚═══╝╚╝ ╚╝

Searching for Spotify directory...

Found Spotify Directory: /var/lib/flatpak/app/com.spotify.Client/x86_64/stable/636d85b350ab6c1e9dc2d259d8305aa5274f8d8ea192ee27a25f7bdb1bcbd155/files/extra/share/spotify

Error: Spotify installation not found.
Install Spotify or set Spotify directory path with '-P' flag.

**Comment by jetfir3** [comment]
Fixed possibility of condition reporting false when cache directory is not found. 

Script should no longer report that installation is not found under these conditions.
