### ISSUE TITLE
Ads not blocked

### ISSUE THREAD

**Issue by OfficialAlienZ** [SpotX-Official/SpotX-Bash#50]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have read the FAQ
- [X] I have checked previous issues, open and closed
- [X] I have completed all troubleshooting steps and the issue is not present on stock but returns after re-applying SpotX-Bash

### Сountry of your account

Italy

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify version: Spotify for macOS (Apple Silicon) 1.2.40.599.g606b7f29
- OS: Sonoma 14.5
- Shell: zsh
```

### 📝 Description

1. Start playback
2. After 10 tracks or so, an ad is played

### 🖥️ Terminal Input/Output

bash <(curl -sSL https://spotx-official.github.io/run.sh) -p -B -f -d --installmac
Latest supported version: 1.2.40.599
Requested Spotify version: 1.2.40.599

######################################################################### 100.0%
✔ Downloaded and installing Spotify
✔ Installed in '/Applications'
✔ Created backup
✔ Detected premium-tier plan
✔ Enabled developer mode
✔ Enabled experimental features
✔ Blocked automatic updates
✔ Codesigned Spotify
✔ Finished

**Comment by jetfir3** [comment]
> 
>  ✔ Detected premium-tier plan 

This says it all right here. You enabled premium option but you do not pay for premium, therefore it should not be used.

Re-run after removing -p.
