### ISSUE TITLE
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to spotx-official.github.io:443 

### ISSUE THREAD

**Issue by gradygambrell** [SpotX-Official/SpotX-Bash#51]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have read the FAQ
- [X] I have checked previous issues, open and closed
- [X] I have completed all troubleshooting steps and the issue is not present on stock but returns after re-applying SpotX-Bash

### Сountry of your account

United States

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify version: None
- OS: macOS 14.5
- Shell: bash
```

### 📝 Description

1. Run command...
2. Error popped up.

### 🖥️ Terminal Input/Output

`test@Test-Air ~ % bash <(curl -sSL https://spotx-official.github.io/run.sh)
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to spotx-official.github.io:443 `

**Comment by jsmaud** [comment]
I realise this was a while ago but I am now facing this issue. What was your solution?
