### ISSUE TITLE
curl: (35) Recv failure: Connection reset by peer

### ISSUE THREAD

**Issue by aepmqr** [SpotX-Official/SpotX-Bash#53]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have read the FAQ
- [X] I have checked previous issues, open and closed
- [X] I have completed all troubleshooting steps and the issue is not present on stock but returns after re-applying SpotX-Bash

### Сountry of your account

Philippines

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify version: Spotify for macOS (Intel)
1.2.42.290.g242057a2
- OS: macOS Monterey 12.7.5
- Shell: -zsh 80x24
```

### 📝 Description

1. Copied and pasted : % bash <(curl -sSL https://spotx-official.github.io/run.sh)
2. This error popped up: curl: (35) Recv failure: Connection reset by peer
3. It usually works before but it gave me this error
...
I only follow what it told me to do, idk how to make it work. Please help. I don't know anything about these type of stuff, so please help me.

### 🖥️ Terminal Input/Output

 % bash <(curl -sSL https://spotx-official.github.io/run.sh)
curl: (35) Recv failure: Connection reset by peer

**Comment by jetfir3** [comment]
curl issues are problems between your network and GitHub servers.. unrelated to SpotX itself.

curl issues are covered in FAQ - https://github.com/SpotX-Official/SpotX-Bash/wiki/SpotX%E2%80%90Bash-FAQ#why-does-spotx-bash-say-failed-to-connect-could-not-be-resolved-or-other-curl-errors

use the alternate link, change networks or download and run script locally... just as the FAQ explains. 

do not fill out bug template saying you read the FAQ and previous issues if you did not.
