### ISSUE TITLE
How to get this working on NixOS?

### ISSUE THREAD

**Issue by iamstonecutter** [SpotX-Official/SpotX-Bash#54]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have read the FAQ
- [X] I have checked previous issues, open and closed
- [X] I have completed all troubleshooting steps and the issue is not present on stock but returns after re-applying SpotX-Bash

### Сountry of your account

USA

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify version: 1.2.40.599.g606b7f29
- OS: NixOS
- Shell: bash
```

### 📝 Description

1. Script does not work on NixOS
2.
3.
...

### 🖥️ Terminal Input/Output

bash <(curl -sSL https://spotx-official.github.io/run.sh)

I run this command and the output is a flood of what you see in the screenshot image I provided to this post.

### 📸 Screenshots

![image](https://github.com/user-attachments/assets/289af4c4-159d-4318-bd1f-ad3321a33dae)

**Comment by jetfir3** [comment]
If you had read the FAQ or previous issues like you said you did, you would have found this:
https://github.com/SpotX-Official/SpotX-Bash/issues/38
