### ISSUE TITLE
Mac Firewall automatically blocks Spotify network connection

### ISSUE THREAD

**Issue by AndDevDE** [SpotX-Official/SpotX-Bash#55]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have read the FAQ
- [X] I have checked previous issues, open and closed
- [X] I have completed all troubleshooting steps and the issue is not present on stock but returns after re-applying SpotX-Bash

### Сountry of your account

Germany

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify version: Spotify für macOS (Apple Silicon) 1.2.42.290.g242057a2
- OS: 15.0 Beta (24A5298h)
- Shell: bash
```

### 📝 Description

1. Enable Mac Firewall (if not enabled)
2. Open Spotify (Spotify shows you are offline)
3. Go into Mac Firewall options and manually set Spotify to allow incomming connections
4. Spotify still shows no connection
5. Close and Reopen Settings and the setting is set to not allow incoming connection again
6. Spotify can only be used when Mac Firewall is completely turned off (Which I don't want)

### 🖥️ Terminal Input/Output

bash <(curl -sSL https://spotx-official.github.io/run.sh)

Latest supported version: 1.2.43.420
Detected client version: 1.2.42.290

✔ Detected & restored backup
✔ Applied free-tier plan patches
✔ Enabled experimental features
✔ Codesigned Spotify
✔ Finished

**Comment by jetfir3** [comment]
So running the following command allows Spotify to work again?
```
bash <(curl -sSL https://spotx-official.github.io/run.sh) --uninstall
```

**Comment by jetfir3** [comment]
1 week no response and this appears to be a macOS issue, unrelated to SpotX-Bash entirely. Closing...

Look into resolving the bug in macOS firewall or skip the macOS firewall entirely and use something like Lulu or Little Snitch for a more robust firewall alternative.
