### ISSUE TITLE
 Symbol not found: _locale_charset

### ISSUE THREAD

**Issue by kvlq** [SpotX-Official/SpotX-Bash#57]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have read the FAQ
- [X] I have checked previous issues, open and closed
- [X] I have completed all troubleshooting steps and the issue is not present on stock but returns after re-applying SpotX-Bash

### Сountry of your account

Romania

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify version: Spotify for macOS (Apple Silicon) 1.2.39.578.g0ea3f38b
- OS: Version 15.1 Beta (24B5024e)
- Shell:
```

### 📝 Description

1. Install latest line command tools (Command Line Tools for Xcode 16 beta 5) from Apple website [https://download.developer.apple.com/Developer_Tools/Command_Line_Tools_for_Xcode_16_beta_5/Command_Line_Tools_for_Xcode_16_beta_5.dmg](url)
2. Ran " bash <(curl -sSL https://spotx-official.github.io/run.sh) " in terminal.

### 🖥️ Terminal Input/Output

bash <(curl -sSL https://spotx-official.github.io/run.sh)
dyld[18049]: Symbol not found: _locale_charset
  Referenced from: <048CD29D-401C-3C6F-8510-0E061FCC7B40> /opt/local/bin/bash
  Expected in:     <9521588A-E5D2-3C93-A726-0EF520C9A854> /opt/local/lib/libiconv.2.dylib
[1]    18049 abort      bash <(curl -sSL https://spotx-official.github.io/run.sh)
curl: (23) Failed writing body

**Comment by jetfir3** [comment]
Based on your output, it suggests that this error is unrelated to SpotX-Bash script and has to do with:
_dyld[18049]: Symbol not found: _locale_charset
Referenced from: <048CD29D-401C-3C6F-8510-0E061FCC7B40> /opt/local/bin/bash
Expected in: <9521588A-E5D2-3C93-A726-0EF520C9A854> /opt/local/lib/libiconv.2.dylib_

It would suggest an issue between your bash and libiconv.2.dylib binaries. Those binary paths do not look to be standard macOS locations for bash. Using the default macOS bash binary or fixing your current setup should hopefully resolve the error.

**Comment by kvlq** [comment]
I've been searching for like the past 4hrs for a solution but can't get it working. 
How can i fix it or use the default macOS bash? I do not remember installing anything related to git/bash on my machine other than what was already installed by default...

**Comment by jetfir3** [comment]
Based on the paths in your error, it suggests you have used macports at some point to install bash.

Does `/bin/bash` binary exist on macOS 15.x?  You'd then be able to run:
```
/bin/bash <(curl -sSL https://spotx-official.github.io/run.sh)
```

If not, I'd suggest using homebrew to install bash/update and use that. 

Your bash binary which is being used @ /opt/local/bin/bash is expecting and referencing "locale_charset" in the /opt/local/lib/libiconv.2.dylib binary, however "locale_charset" missing in /opt/local/lib/libiconv.2.dylib, therefore bash fails to continue running and you get the error you are seeing.

**Comment by jetfir3** [comment]
Interesting. So it seems macOS beta 15.1 has some bugs and they need to rebuild either their bash and/or libiconv.2.dylib binaries based on what I'm seeing in your errors. 

As for the homebrew permission issue.. it seems you're using the bash directory path and not the binary path. An example of the full path would be:
/opt/homebrew/Cellar/bash/<bash version here>/bin/bash

This entire issue seems unrelated to SpotX-Bash at this point and has become a macOS 15.1 beta bugs and/or how to install and setup bash with homebrew.

**Comment by kvlq** [comment]
Yes, seems like that. Thank you for your support. You can close the issue.

**Comment by jetfir3** [comment]
Curious what your output from the following is...
```
/opt/homebrew/bin/bash <(curl -sSL https://spotx-official.github.io/run.sh)
```

still permission issue?

**Comment by kvlq** [comment]
![CleanShot 2024-08-14 at 20 45 36@2x](https://github.com/user-attachments/assets/f1cd0132-a5b4-49aa-94dd-a9525ed2f5de)

**Comment by jetfir3** [comment]
Very odd. And the repo alternate link in FAQ produces same error?

```
bash <(curl -sSL https://raw.githubusercontent.com/SpotX-Official/SpotX-Bash/main/spotx.sh)
```


does downloading the file and running locally also produce an error?
```
curl -LO https://raw.githubusercontent.com/SpotX-Official/SpotX-Bash/main/spotx.sh && chmod +x ./spotX.sh && bash ./spotX.sh
```

**Comment by kvlq** [comment]
![CleanShot 2024-08-14 at 21 03 19@2x](https://github.com/user-attachments/assets/497498f4-d701-4955-9d6c-10315eca67fb)

damn...

**Comment by kvlq** [comment]
Seems that it worked with sh.
`sh <(curl -sSL https://raw.githubusercontent.com/SpotX-Official/SpotX-Bash/main/spotx.sh)`

![CleanShot 2024-08-14 at 21 07 31@2x](https://github.com/user-attachments/assets/577a2e4f-25fe-45c1-b3f3-82a4a938c150)

**Comment by kvlq** [comment]
Yes..
![CleanShot 2024-08-14 at 21 13 56@2x](https://github.com/user-attachments/assets/2edb8fed-880c-4d51-ac2e-da4387b99ef2)

**Comment by jetfir3** [comment]
> Yes.. 

Well that confirms it's 100% unrelated to something in SpotX-Bash. I'll assume this is just something broken in the macOS beta. 

If this gets resolved for you in a future beta or stable update, please report back if you think of it. Curious wtf is going on and hoping an update resolves this. 

For future reference, if macOS users run into this issue... users should attempt using `sh` instead of `bash`. 

Closing this for now...
