### ISSUE TITLE
Fails to download client on Ubuntu

### ISSUE THREAD

**Issue by satabios** [SpotX-Official/SpotX-Bash#58]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have read the FAQ
- [X] I have checked previous issues, open and closed
- [X] I have completed all troubleshooting steps and the issue is not present on stock but returns after re-applying SpotX-Bash

### Сountry of your account

USA

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify version:  1.2.42.290
- OS: Ubuntu 22.04
- Shell: zsh
```

### 📝 Description

1.Ran the command bash <(curl -sSL https://spotx-official.github.io/run.sh) --installdeb
The curl fails the download the package as shown below

### 🖥️ Terminal Input/Output

 bash <(curl -sSL https://spotx-official.github.io/run.sh) --installdeb

████╗███╗  ███╗ █████╗█╗  █╗  ███╗  ██╗ ████╗█╗ █╗
█╔══╝█╔═█╗█╔══█╗╚═█╔═╝╚█╗█╔╝  █╔═█╗█╔═█╗█╔══╝█║ █║
████╗███╔╝█║  █║  █║   ╚█╔╝██╗███╔╝████║████╗████║
╚══█║█╔═╝ █║  █║  █║   █╔█╗╚═╝█╔═█╗█╔═█║╚══█║█╔═█║
████║█║   ╚███╔╝  █║  █╔╝ █╗  ███╔╝█║ █║████║█║ █║
╚═══╝╚╝    ╚══╝   ╚╝  ╚╝  ╚╝  ╚══╝ ╚╝ ╚╝╚═══╝╚╝ ╚╝

Latest supported version: 1.2.45.454
Requested client version: 1.2.42.290

######################################################################################################################################                                                                                      61.8%curl: (18) transfer closed with 52416566 bytes remaining to read

Error: Client download failed

**Comment by jetfir3** [comment]
This is an issue between your network and Spotify's server where the Deb is hosted (mostly Spotify's server).

1. Keep trying until you have success.
2. Skip downloading/installing the client via SpotX-Bash and use APT, package manager of choice or other methods to install the stock client first then run SpotX-Bash on it (without --installdeb flag).
