### ISSUE TITLE
Why do these appear, and what do I choose.

### ISSUE THREAD

**Issue by wakmail** [SpotX-Official/SpotX-Bash#59]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have read the FAQ
- [X] I have checked previous issues, open and closed
- [X] I have completed all troubleshooting steps and the issue is not present on stock but returns after re-applying SpotX-Bash

### Сountry of your account

US

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify version: 
- OS: 
- Shell:
```

### 📝 Description

1.
2.
3.
...

### 🖥️ Terminal Input/Output

bash <(curl -sSL https://spotx-official.github.io/run.sh)

### 📸 Screenshots

![Screenshot 2024-09-13 at 5 56 34 PM](https://github.com/user-attachments/assets/af9d59a3-6574-4665-ab11-e7c51772a76d)

**Comment by amd64fox** [comment]
This issue has been discussed multiple times, it could be found in closed issues [here](https://github.com/SpotX-Official/SpotX-Bash/issues/49) or [here](https://github.com/SpotX-Official/SpotX-Bash/issues/36)

**Comment by jetfir3** [comment]
These popups aren't related to SpotX-Bash and can appear with the stock Spotify app (depending on macOS version -- newer versions have more popups and permissions. 

Connections should always be allowed in order for Spotify to function properly. Access to folders is up to the user, depending on if they want to also add local music into Spotify or not.
