### ISSUE TITLE
[macOS] SpotX-Bash could not resolve host

### ISSUE THREAD

**Issue by sfadcs** [SpotX-Official/SpotX-Bash#60]
### 🧐 Have you fully read the README and viewed similar issues?

- [x] I have read the README
- [X] I have read the FAQ
- [X] I have checked previous issues, open and closed
- [X] I have completed all troubleshooting steps and the issue is not present on stock but returns after re-applying SpotX-Bash

### Сountry of your account

Canada

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify version: Spotify for macOS (Apple Silicon) 1.2.45.454.gc16ec9f6
- OS: MacOS Monterey 12.6
- Shell: -zsh
```

### 📝 Description

1. Ads started appearing on spotify again
2. used the command bash <(curl -sSL https://spotx-official.github.io/run.sh) in terminal
3. got back Could not resolve host: spotx-official.github.io
4. uninstalled and reinstalled spotxbash
5. ran through all troubleshooting steps
...

### 🖥️ Terminal Input/Output

_[my computer name]_ ~ % bash <(curl -sSL https://spotx-official.github.io/run.sh)
curl: (6) Could not resolve host: spotx-official.github.io

**Comment by jetfir3** [comment]
Doesn't sound like you read the FAQ: [Why does SpotX-Bash say "Failed to connect", "Could not be resolved" or other cURL errors?](https://github.com/SpotX-Official/SpotX-Bash/wiki/SpotX%E2%80%90Bash-FAQ#why-does-spotx-bash-say-failed-to-connect-could-not-be-resolved-or-other-curl-errors)

There's an issue between you and the URL in your command -- the FAQ provides an alternate link and also mentions that downloading and running the file locally is also an option if curl fails. 

If you do not block updates using SpotX-Bash (`-B`) then Spotify will auto-update itself which then removes all patches until SpotX-Bash is used again to patch the updated app.
