### ISSUE TITLE
SpotX-Bash does not have write permission in client directory but directory is in my $HOME

### ISSUE THREAD

**Issue by KAGEYAM4** [SpotX-Official/SpotX-Bash#61]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have read the FAQ
- [X] I have checked previous issues, open and closed
- [X] I have completed all troubleshooting steps and the issue is not present on stock but returns after re-applying SpotX-Bash

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

###  Computer information

```markdown
- Spotify version: 1.2.47.364
- OS: ArchLinux
- Shell: bash 5.2.32
```

### 📝 Description

```
Searching for client directory...

Found client Directory: ~/.local/share/spotify-launcher/install/usr/share/spotify

Latest supported version: 1.2.47.364
Detected client version: 1.2.47.364

Warning: SpotX-Bash does not have write permission in client directory.
Requesting sudo permission...
Password: 
```

```
drwxr-xr-x - phoenix phoenix 27 Sep 22:08 /home/phoenix/.local/share/spotify-launcher/install/usr/share/spotify
```

Why is it asking for sudo when i own the directory? 

This is spotify i am using - https://archlinux.org/packages/extra/x86_64/spotify-launcher/

**Comment by AvAkanksh** [comment]
even i had the same doubt, but i have the permission without any thinking. When i play the songs they are getting paused after some time. not sure how to fix that as well.

**Comment by jetfir3** [comment]
> Why is it asking for sudo when i own the directory?

Script checked if the following paths were writable:
/home/phoenix/.local/share/spotify-launcher/install/usr/share/spotify
/home/phoenix/.local/share/spotify-launcher/install/usr/share/spotify/spotify
/home/phoenix/.local/share/spotify-launcher/install/usr/share/spotify/Apps
/home/phoenix/.local/share/spotify-launcher/install/usr/share/spotify/Apps/xpui.spa

at least one of them returned that it was not writable so elevated permissions were requested.

**Comment by KAGEYAM4** [comment]
> > Why is it asking for sudo when i own the directory?
> 
> Script checked if the following paths were writable: /home/phoenix/.local/share/spotify-launcher/install/usr/share/spotify /home/phoenix/.local/share/spotify-launcher/install/usr/share/spotify/spotify /home/phoenix/.local/share/spotify-launcher/install/usr/share/spotify/Apps /home/phoenix/.local/share/spotify-launcher/install/usr/share/spotify/Apps/xpui.spa
> 
> at least one of them returned that it was not writable so elevated permissions were requested.

I tried this command `find .local/share/spotify-launcher/ -not -user phoenix` and no output was given. that means eveything is owned by me in that directory.

**Comment by jetfir3** [comment]
> Will ask package developer to add the write permission.

A normal user not modifying their Spotify client would not need the Spotify executable writable -- the spotify-launcher repo should probably not make it writable by default.. though perhaps they could add some sort of flag/option.

**Comment by KAGEYAM4** [comment]
> > Will ask package developer to add the write permission.
> 
> A normal user not modifying their Spotify client would not need the Spotify executable writable -- the spotify-launcher repo should probably not make it writable by default.. though perhaps they could add some sort of flag/option.

I already opened issue on their repo. What do you suggest i should ask for? As this was working previously and broke with recent update.

**Comment by KAGEYAM4** [comment]
@jetfir3  Lets say i gave sudo permission, who will own that directory after SpotX completes? Will it be root?

I have not got any response from https://github.com/kpcyrd/spotify-launcher but do you think maybe Spot-X can check if the directory is owned by user who ran Spot-X and if yes, then it can add write permission and do its work and optionally restore permission changes.

**Comment by jetfir3** [comment]
> Lets say i gave sudo permission, who will own that directory after SpotX completes? Will it be root?

yes

SpotX-Bash won't be changing how it handles permissions. If user does not own every Spotify directory/file needed for patching then sudo will be requested. If you have a directory or file which is not owned by your user and do not want permissions to change to root, modify Spotify directory/file permissions before running SpotX-Bash.
