### ISSUE TITLE
Command doesn't seem to work

### ISSUE THREAD

**Issue by domi413** [SpotX-Official/SpotX-Bash#62]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have read the FAQ
- [X] I have checked previous issues, open and closed
- [X] I have completed all troubleshooting steps and the issue is not present on stock but returns after re-applying SpotX-Bash

### Сountry of your account

Switzerland

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify version: 1.2.47.364.gf06e5cee
- OS: Arch
- Shell: fish, version 3.7.1
```

### 📝 Description

1. Run `bash <(curl -sSL https://spotx-official.github.io/run.sh)` in terminal

### 🖥️ Terminal Input/Output

*empty*

### 📸 Screenshots

![image](https://github.com/user-attachments/assets/8bba3343-3c21-45b7-b952-f944c760aba9)

**Comment by jetfir3** [comment]
Didn't read previous issues. Dupe issue. https://github.com/SpotX-Official/SpotX-Bash/issues/8

**Comment by jetfir3** [comment]
> I have the same issue using bash:

No, this is now a new issue. And this issue is covered in previous closed issues as well as the FAQ -- https://github.com/SpotX-Official/SpotX-Bash/issues/60
