### ISSUE TITLE
SSL Error/Down

### ISSUE THREAD

**Issue by asdat3** [SpotX-Official/SpotX-Bash#66]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have read the FAQ
- [X] I have checked previous issues, open and closed
- [X] I have completed all troubleshooting steps and the issue is not present on stock but returns after re-applying SpotX-Bash

### Сountry of your account

germnay

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

Yes

### ℹ Computer information

```markdown
- Spotify version: 
- OS: 
- Shell:
```

### 📝 Description

Not sure if it is actually on your end but since that was the issue on 3 networks for me already I believe so, running through the github url works fine:
bash <(curl -sSL https://raw.githubusercontent.com/SpotX-Official/SpotX-Bash/refs/heads/main/spotx.sh)

### 🖥️ Terminal Input/Output

`Downloads % bash <(curl -sSL https://spotx-official.github.io/run.sh)
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to spotx-official.github.io:443`

**Comment by jetfir3** [comment]
Thanks for the report. 

Unfortunately, *.GitHub.io is managed by GitHub and I have no say in the matter. Some users have issues with the domain... most don't. More regions/networks seem to have issues with raw.githubusercontent.com than *.GitHub.io so the .io domain was chosen as the default. 

Multiple domains are mentioned in the FAQ to cover this issue.
